/**
 * Generates supabase/seed.sql from lib/demo/dataset.ts so the SQL seed and the
 * in-app "Reset demo" action always contain the same simulated data.
 *
 *   npm run db:seed:generate
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildDemoDataset, type DemoDataset } from "../lib/demo/dataset";

const RAW = "__SQL__:";
const time = (minutesAgo: number) =>
  minutesAgo >= 0
    ? `${RAW}now() - interval '${minutesAgo} minutes'`
    : `${RAW}now() + interval '${-minutesAgo} minutes'`;

const TEXT_ARRAY_COLUMNS = new Set(["equipment"]);

function literal(column: string, value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "string") {
    if (value.startsWith(RAW)) return value.slice(RAW.length);
    return `'${value.replace(/'/g, "''")}'`;
  }
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (Array.isArray(value) && TEXT_ARRAY_COLUMNS.has(column)) {
    return `array[${value.map((v) => literal(column, String(v))).join(", ")}]::text[]`;
  }
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function inserts(table: string, rows: Record<string, unknown>[]): string {
  return rows
    .map((row) => {
      const cols = Object.keys(row).filter((k) => row[k] !== undefined);
      return `insert into public.${table} (${cols.join(", ")})\nvalues (${cols
        .map((c) => literal(c, row[c]))
        .join(", ")});`;
    })
    .join("\n");
}

const data: DemoDataset = buildDemoDataset(time);
const sosIds = data.sos_requests.map((s) => `'${s.id}'`).join(", ");

const sql = `-- JalSuraksha Nepal — demo seed data
-- GENERATED by scripts/generate-seed.ts from lib/demo/dataset.ts. Do not edit by hand.
--
-- ALL DATA BELOW IS SIMULATED for the hackathon demo ("${"JalSuraksha Hackathon Demo"}").
-- Locations are approximate; facility names are illustrative; phone numbers are fake.

begin;

${inserts("rescue_teams", data.rescue_teams)}

${inserts("alerts", data.alerts)}

${inserts("risk_zones", data.risk_zones)}

${inserts("shelters", data.shelters)}

${inserts("hazard_reports", data.hazard_reports)}

${inserts("sos_requests", data.sos_requests)}

-- Replace the automatic "received" entries with the scripted history.
delete from public.incident_status_history where sos_id in (${sosIds});

${inserts("incident_status_history", data.incident_status_history)}

${inserts("rescue_assignments", data.rescue_assignments)}

commit;
`;

const out = resolve(__dirname, "../supabase/seed.sql");
writeFileSync(out, sql);
console.log(
  `Wrote ${out}: ${data.alerts.length} alerts, ${data.risk_zones.length} zones, ${data.shelters.length} shelters, ` +
    `${data.rescue_teams.length} teams, ${data.hazard_reports.length} hazards, ${data.sos_requests.length} SOS, ` +
    `${data.rescue_assignments.length} assignments, ${data.incident_status_history.length} history rows`,
);
